# js 基础

## 深拷贝

```js
/**
 * 深拷贝
 * @param {Object} obj 要拷贝的对象
 */
function deepClone(obj = {}) {
  if (typeof obj !== 'object' || obj == null) {
    // obj 是 null ，或者不是对象和数组，直接返回
    return obj
  }

  // 初始化返回结果
  let result
  if (obj instanceof Array) {
    result = []
  } else {
    result = {}
  }

  for (let key in obj) {
    // 保证 key 不是原型的属性
    if (obj.hasOwnProperty(key)) {
      // 递归调用！！！
      result[key] = deepClone(obj[key])
    }
  }

  // 返回结果
  return result
}
```

## 原型原型链

1. 如何判断一个变量是不是数组

2. 手写一个简易的 jQuery, 考虑插件和扩展性

3. class 的原型本质, 怎么理解

## instanceof

用于检测构造函数的 prototype 属性是否出现在某个实例对象的原型上

```js
// 判断 [] 是不是 Array 的class 构建出来的
//
;[] instanceof Array // true
```

## event loop(事件循环/事件轮询)

## Promise(原理)

- 三种状态

```js
// pending(等待) resolved(成功) rejected(失败)
// pending => resolved 或者 pending => rejected
// 变化不可逆, 没发把成功变成失败

// 刚定义时，状态默认为 pending
const p1 = new Promise((resolve, reject) => {})

// 执行 resolve() 后，状态变成 resolved
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve()
  })
})

// 执行 reject() 后，状态变成 rejected
const p3 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject()
  })
})
```

- 状态的表现和变化

1. `pending` 状态, 不会触发 then 和 catch

2. `resolve` 状态, 会触发后续的 then 回调函数

3. `rejected` 状态, 会触发后续的 catch 回调函数

- then 和 catch 对状态的影响

1. `then` 正常返回 resolved, 里面有报错则返回 rejected

2. `catch` 正常返回 resolved, 里面有报错则返回 rejected

> 题目演示

[![cvTChF.png](https://z3.ax1x.com/2021/04/25/cvTChF.png)](https://imgtu.com/i/cvTChF)

```js
// then() 一般正常返回 resolved  状态的 promise
Promise.resolve().then(() => {
  return 100
})

// then() 里抛出错误，会返回 rejected 状态的 promise
Promise.resolve().then(() => {
  throw new Error('err')
})
```

## async/await

- 异步回调地域(场景)

- Promise, then, catch 是链式调用, 但也是基于回调函数

- async/await 是同步语法, 彻底消灭回调函数

## async/await 和 Promise 的关系

- 执行 async 函数, 返回的是 Promise 对象

- await 相当于 Promise 的 then

- try...catch 可以捕获异常, 代替了 Promise 的 catch
